USE [master]
GO
/****** Object:  Database [capgemini]    Script Date: 2018-06-18 00:48:47 ******/
CREATE DATABASE [capgemini]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'capgemini', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\capgemini.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'capgemini_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\capgemini_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [capgemini] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [capgemini].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [capgemini] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [capgemini] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [capgemini] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [capgemini] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [capgemini] SET ARITHABORT OFF 
GO
ALTER DATABASE [capgemini] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [capgemini] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [capgemini] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [capgemini] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [capgemini] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [capgemini] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [capgemini] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [capgemini] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [capgemini] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [capgemini] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [capgemini] SET  DISABLE_BROKER 
GO
ALTER DATABASE [capgemini] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [capgemini] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [capgemini] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [capgemini] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [capgemini] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [capgemini] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [capgemini] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [capgemini] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [capgemini] SET  MULTI_USER 
GO
ALTER DATABASE [capgemini] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [capgemini] SET DB_CHAINING OFF 
GO
ALTER DATABASE [capgemini] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [capgemini] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [capgemini]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 2018-06-18 00:48:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Customer](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Surname] [varchar](100) NOT NULL,
	[Phone] [varchar](50) NULL,
	[Address] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[Customer] ON 

INSERT [dbo].[Customer] ([ID], [Name], [Surname], [Phone], [Address]) VALUES (2, N'Mirosław', N'Gab', N'45345345345', N'KK')
INSERT [dbo].[Customer] ([ID], [Name], [Surname], [Phone], [Address]) VALUES (5, N'Beata', N'Ga', N'345345345777', N'kk')
INSERT [dbo].[Customer] ([ID], [Name], [Surname], [Phone], [Address]) VALUES (7, N'Beata', N'Ga', N'+48 54353453225', N'some city')
SET IDENTITY_INSERT [dbo].[Customer] OFF
USE [master]
GO
ALTER DATABASE [capgemini] SET  READ_WRITE 
GO
